set_property IOSTANDARD LVCMOS18 [get_ports {a[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {a[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {a[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {a[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {b[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {b[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {b[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {b[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {s[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {s[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {s[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {s[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports cin]

set_property IOSTANDARD LVCMOS18 [get_ports c]
