create_clock -period 10.000 -name sys_clk [get_ports clk]


set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports hr_set]
set_property IOSTANDARD LVCMOS33 [get_ports min_set]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property PACKAGE_PIN J2 [get_ports hr_set]
set_property PACKAGE_PIN J5 [get_ports min_set]
set_property PACKAGE_PIN J1 [get_ports rst]
set_property PACKAGE_PIN F14 [get_ports clk]

set_property IOSTANDARD LVCMOS33 [get_ports {AN[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[0]}]

set_property PACKAGE_PIN H3 [get_ports {AN[0]}]
set_property PACKAGE_PIN J4 [get_ports {AN[1]}]
set_property PACKAGE_PIN F3 [get_ports {AN[2]}]
set_property PACKAGE_PIN E4 [get_ports {AN[3]}]
set_property PACKAGE_PIN D5 [get_ports {AN[4]}]
set_property PACKAGE_PIN C4 [get_ports {AN[5]}]
set_property PACKAGE_PIN C7 [get_ports {AN[6]}]
set_property PACKAGE_PIN A8 [get_ports {AN[7]}]
set_property PACKAGE_PIN F4 [get_ports {seg[0]}]
set_property PACKAGE_PIN J3 [get_ports {seg[1]}]
set_property PACKAGE_PIN D2 [get_ports {seg[2]}]
set_property PACKAGE_PIN C2 [get_ports {seg[3]}]
set_property PACKAGE_PIN B1 [get_ports {seg[4]}]
set_property PACKAGE_PIN H4 [get_ports {seg[5]}]
set_property PACKAGE_PIN D1 [get_ports {seg[6]}]
set_property PACKAGE_PIN C1 [get_ports {seg[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports {seg1[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg1[0]}]
set_property PACKAGE_PIN D7 [get_ports {seg1[0]}]
set_property PACKAGE_PIN C5 [get_ports {seg1[1]}]
set_property PACKAGE_PIN A5 [get_ports {seg1[2]}]
set_property PACKAGE_PIN B7 [get_ports {seg1[3]}]
set_property PACKAGE_PIN A7 [get_ports {seg1[4]}]
set_property PACKAGE_PIN D6 [get_ports {seg1[5]}]
set_property PACKAGE_PIN B5 [get_ports {seg1[6]}]
set_property PACKAGE_PIN A6 [get_ports {seg1[7]}]

set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]


set_property CONFIG_MODE SPIx4 [current_design]

set_property IOSTANDARD LVCMOS33 [get_ports day_set]
set_property PACKAGE_PIN H2 [get_ports day_set]
