create_clock -period 10.000 -name sys_clk [get_ports clk]

set_property IOSTANDARD LVCMOS33 [get_ports {col[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {col[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {col[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {col[0]}]

##PULLUP
set_property PULLTYPE PULLUP [get_ports {col[0]}]
set_property PULLTYPE PULLUP [get_ports {col[1]}]
set_property PULLTYPE PULLUP [get_ports {col[2]}]
set_property PULLTYPE PULLUP [get_ports {col[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports {key_bin[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key_bin[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key_bin[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key_bin[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN F14 [get_ports clk]
set_property PACKAGE_PIN J1 [get_ports rst]
set_property PACKAGE_PIN T6 [get_ports {col[3]}]
set_property PACKAGE_PIN T5 [get_ports {col[2]}]
set_property PACKAGE_PIN R5 [get_ports {col[1]}]
set_property PACKAGE_PIN T4 [get_ports {col[0]}]
set_property PACKAGE_PIN R7 [get_ports {row[3]}]
set_property PACKAGE_PIN R6 [get_ports {row[2]}]
set_property PACKAGE_PIN P6 [get_ports {row[1]}]
set_property PACKAGE_PIN P5 [get_ports {row[0]}]
set_property PACKAGE_PIN G1 [get_ports {key_bin[0]}]
set_property PACKAGE_PIN G2 [get_ports {key_bin[1]}]
set_property PACKAGE_PIN F1 [get_ports {key_bin[2]}]
set_property PACKAGE_PIN F2 [get_ports {key_bin[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports unlock]
set_property IOSTANDARD LVCMOS33 [get_ports key_valid]
set_property PACKAGE_PIN E2 [get_ports unlock]
set_property PACKAGE_PIN E3 [get_ports key_valid]

set_property IOSTANDARD LVCMOS33 [get_ports {debug_state[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug_state[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug_state[0]}]


set_property PACKAGE_PIN A3 [get_ports {debug_state[2]}]
set_property PACKAGE_PIN B4 [get_ports {debug_state[1]}]
set_property PACKAGE_PIN A4 [get_ports {debug_state[0]}]
