# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/AND_ip/AND_ip.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AND_ip || ORIG_REF_NAME==AND_ip} -quiet] -quiet

# IP: bd/AND_ip/ip/AND_ip_vio_0_0/AND_ip_vio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AND_ip_vio_0_0 || ORIG_REF_NAME==AND_ip_vio_0_0} -quiet] -quiet

# IP: bd/AND_ip/ip/AND_ip_and_gate_0_0/AND_ip_and_gate_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AND_ip_and_gate_0_0 || ORIG_REF_NAME==AND_ip_and_gate_0_0} -quiet] -quiet

# XDC: e:/VLSI/Verilog/and_gate/and_gate.gen/sources_1/bd/AND_ip/AND_ip_ooc.xdc
