create_clock -period 10.000 -name sys_clk [get_ports clk]

set_property IOSTANDARD LVCMOS33 [get_ports {input_password[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {input_password[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {input_password[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {input_password[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {new_password_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {new_password_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {new_password_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {new_password_out[0]}]
set_property PACKAGE_PIN V2 [get_ports {input_password[0]}]
set_property PACKAGE_PIN U2 [get_ports {input_password[1]}]
set_property PACKAGE_PIN U1 [get_ports {input_password[2]}]
set_property PACKAGE_PIN T2 [get_ports {input_password[3]}]
set_property PACKAGE_PIN A4 [get_ports {new_password_out[0]}]
set_property PACKAGE_PIN B4 [get_ports {new_password_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports ok]
set_property IOSTANDARD LVCMOS33 [get_ports password_change]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports unlock]
set_property PACKAGE_PIN F14 [get_ports clk]
set_property PACKAGE_PIN J5 [get_ports ok]
set_property PACKAGE_PIN M2 [get_ports password_change]
set_property PACKAGE_PIN J1 [get_ports rst]
set_property PACKAGE_PIN G1 [get_ports unlock]

set_property IOSTANDARD LVCMOS33 [get_ports done]
set_property PACKAGE_PIN T1 [get_ports done]

set_property PACKAGE_PIN A3 [get_ports {new_password_out[2]}]
set_property PACKAGE_PIN B3 [get_ports {new_password_out[3]}]
